-- 코드를 입력하세요
SELECT fh.FLAVOR
FROM FIRST_HALF fh
         INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
                     FROM JULY
                     GROUP BY FLAVOR) gj ON fh.FLAVOR = gj.FLAVOR
ORDER BY fh.TOTAL_ORDER + gj.TOTAL_ORDER DESC LIMIT 3;
